
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/crp
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

